name: "Distributed Task Runner"
description: "Executes a list of tasks via bash in parallel."
inputs:
  run:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: 'node20'
  main: 'index.js'
  